{% set version = "dev" %}

package:
  name: nco
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  features:
    - vc14

requirements:
  build:
    - python
    - cmake
    - antlr >=2.7.7,<3
    - curl >=7.44.0,<8
    - expat 2.2.*
    - gsl >=2.2,<2.3
    - hdf5 1.10.1
    - libnetcdf 4.4.*
    - udunits2
    - zlib 1.2.11
    - vc 14
  run:
    - curl >=7.44.0,<8
    - expat 2.2.*
    - gsl >=2.2,<2.3
    - hdf5 1.10.1
    - libnetcdf 4.4.*
    - udunits2
    - vc 14

test:
  source_files:
    - data/in.cdl
  commands:
    - ncks --help
    - ncap2 --help
    - ncks -M "http://tds.marine.rutgers.edu/thredds/dodsC/roms/espresso/2013_da/his/ESPRESSO_Real-Time_v2_History_Best"
